# Generated by Django 6.0.1 on 2026-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0006_escrow_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmilestone',
            name='funded',
            field=models.BooleanField(default=False),
        ),
    ]
