# Generated by Django 6.0.1 on 2026-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0007_jobmilestone_funded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmilestone',
            old_name='completed',
            new_name='released',
        ),
        migrations.AddField(
            model_name='jobmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('submitted', 'Submitted'), ('released', 'Released')], default='pending', max_length=20),
        ),
    ]
