# Generated by Django 6.0.1 on 2026-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0008_rename_completed_jobmilestone_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('funded', 'Funded'), ('released', 'Released')], default='pending', max_length=20),
        ),
    ]
